### PR TITLE
Feat: Edit streams using motions 

### PR DESCRIPTION
**Pull request by iamsamgibbs**
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/2721)

### CODE REVIEW

**Review by jakubcolony — CHANGES_REQUESTED** [review]
Pretty much flawless, top notch work @iamsamgibbs.

I saw a new action type for Edit Streaming Payment added in the schema but can't see it being created anywhere. This would come handy for storing the changes on the action field as explained in the CDapp comment. I think there might be some friction when it comes to cancelling (as we'd need to be careful to only create a cancel action), but feel free to ping me if anything comes up

**Comment by iamsamgibbs** [comment]
> Pretty much flawless, top notch work @iamsamgibbs.
> 
> I saw a new action type for Edit Streaming Payment added in the schema but can't see it being created anywhere. This would come handy for storing the changes on the action field as explained in the CDapp comment. I think there might be some friction when it comes to cancelling (as we'd need to be careful to only create a cancel action), but feel free to ping me if anything comes up

Thanks Jakub! There is already a check in `endTimeSet` to check if the new endTime is equal to the current blocktime and if so assume that this is a cancel action, so hopefully this is already accounted for, but I'll give it a check!

**Review by rumzledz — APPROVED** [review]
Nothing stands out to me and everything is working as expected in the cdapp PR. Awesome stuff @iamsamgibbs ✨

**Review by jakubcolony — APPROVED** [review]
LGTM 👍

**Review by jakubcolony — APPROVED** [review]

**Review by mmioana — APPROVED** [review]
Such a pleasure to look over the code @iamsamgibbs 🤩

**Pull request merged**
