### PR TITLE
Add support for Version Upgrade action

### PR DESCRIPTION
**Pull request by jakubcolony**
This is parallel PR to https://github.com/JoinColony/colonyCDapp/pull/313

### CODE REVIEW

**Review by willm30 — APPROVED** [review]
👏

**Comment by willm30** [comment]
I did just find this in my terminal though, FYI:

error1

**Comment by jakubcolony** [comment]
@willm30 It's an issue with Amplify, I bumped its version yesterday but forgot to push. Could you try running `npm i` after pulling the CDapp branch and see if it's fixed? Thanks

**Comment by willm30** [comment]
@jakubcolony Yup, fixed 👍

**Review by rdig — APPROVED** [review]
Good to go

**Pull request merged**
