### PR TITLE
Send notifications on permissions actions

### PR DESCRIPTION
**Pull request by davecreaser**
See description and testing steps in CDapp PR: https://github.com/JoinColony/colonyCDapp/pull/3205

### CODE REVIEW

**Review by bassgeta — APPROVED** [review]
Approving since I've tested its CDapp counterpart, looking good and simple!

**Review by mmioana — APPROVED** [review]
Really nice and simple solution @davecreaser 🌟 
Tested as part of the [colonyCDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3205#pullrequestreview-2347464579)

@davecreaser I have just a curiosity, is there a reason for which we don't `await` the `sendActionNotifications` calls?

**Review by iamsamgibbs — APPROVED** [review]
Tested with the CDapp counterpart, these all look like sensible changes. Nice job!

**Comment by davecreaser** [comment]
> Really nice and simple solution @davecreaser 🌟 Tested as part of the [colonyCDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3205#pullrequestreview-2347464579)
> 
> @davecreaser I have just a curiosity, is there a reason for which we don't `await` the `sendActionNotifications` calls?

Yeah, It's basically just so they aren't blocking anything else. It's not crucial that they are sent immediately, so they shouldn't block other, more important things and instead should just be completed whenever the resources are available :)

**Pull request merged**
