### PR TITLE
[Notifications] feat: send notifications on new extension versions

### PR DESCRIPTION
**Pull request by bassgeta**
[CDapp PR](https://github.com/JoinColony/colonyCDapp/pull/3358)

### CODE REVIEW

**Review by rdig — APPROVED** [review]
Nicely done here as well! Tested as part of the review of JoinColony/colonyCDapp#3358

**Review by mmioana — APPROVED** [review]
Nice nice nice 👍 

Tested as part of the [CDapp counterpart](https://github.com/JoinColony/colonyCDapp/pull/3358#pullrequestreview-2374873035)

**Review by rdig — APPROVED** [review]
Re-tested this as part of the review of JoinColony/colonyCDapp#3358, specifically https://github.com/JoinColony/colonyCDapp/pull/3358#pullrequestreview-2375470680

Nice job on filtering out the unused extensions :+1:

**Review by davecreaser — APPROVED** [review]
Very nice, tested as part of the CDapp PR. 🚀  Good to go!

**Pull request merged**
